name: Test

on: [push, pull_request]
jobs:
  test:
    services:
      mongodb:
        image: mongo:3.6
        env:
          MONGO_INITDB_DATABASE: fiddles
        ports:
          - 27017:27017
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["12", "*"]
    name: Test ${{ matrix.node }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - name: Build the app
        run: npm run build
      
      - name: Test app
        run: npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/fiddles
          SESSION_SECRET: keyboard-cat
